version: '3'

services:
  app:
    container_name: lifeguard
    external_links:
      - db-postgres:db
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "4000:3000"
    command: bash server.sh 3000 development
    depends_on:
      - assets

  assets:
    build:
      context: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8090:8090"
    command: npm run dev

networks:
  default:
    external:
      name: db-backend
