defaults: &defaults
  username: dennis
  password:
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *defaults
  database: lifeguard_development

test:
  <<: *defaults
  database: lifeguard_test
