defaults: &defaults
  username: db-user
  password:
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  port: 5432

development:
  <<: *defaults
  database: lifeguard_development

test:
  <<: *defaults
  database: lifeguard_test
